name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Run my script
      run: |
        python ./my_script.py
    # runs-on: ubuntu-latest
    # steps:
    #   - name: 'Checkout codes'
    #     uses: actions/checkout@v1

    #   - name: Set up python 3.8
    #     uses: actions/setup-python@v2
    #     with:
    #       python-version: '3.8'

    #   - name: Run my script
    #     run: python ./my_script.py

    - name: 'Get Weather'
      run: bash ./weather.sh
    - name: 'Get Date'
      run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"

    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: from roccoshi's test ':' (${{env.REPORT_DATE}})
        
        body: file://list.txt, ./text.html
        to: roccoshi@qq.com
        from: GitHub Actions
        content_type: text/html