name: 'newsexpress --roccoshi'

on:
  push:
  schedule:
     - cron: '0 4,13 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        presist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Run my script
      run: |
        python ./my_script.py

    - name: 'Get Date'
      run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"

    - name: 'Check Update'
      run: |
        vartext=$(cat ./update)
        echo "::set-env name=SHOULD_UPDATE::${vartext}"
      shell: bash

    - name: 'Send mail'
      if: ${{env.SHOULD_UPDATE=='true'}}
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 来自roccoshi的西电每日通知快送 (${{env.REPORT_DATE}})
        
        body: file://text.html
        to: ${{ secrets.MAIL_LIST }}
        from: GitHub Actions
        content_type: text/html

    - name: commit
      run: |
        git config --global user.email 474617032@qq.com
        git config --global user.name Lincest
        git add .
        git commit -m "update" -a
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
