name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '* */5 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run my script
        run: python ./my_script.py

      # - name: 'Get Weather'
      #   run: bash ./weather.sh
      # - name: 'Get Date'
      #   run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      # - name: 'Send mail'
      #   uses: dawidd6/action-send-mail@master
      #   with:
      #     server_address: smtp.163.com
      #     server_port: 465
      #     username: ${{ secrets.MAIL_USERNAME }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     subject: 来自rocco weather bot ： YueYang Weather Report (${{env.REPORT_DATE}})
      #     body: file://result.html
      #     to: 1151695676@qq.com,roccoshi@qq.com,hotog@qq.com
      #     from: GitHub Actions
      #     content_type: text/html